export const AppState = {
  LANDING: 'LANDING',
  DASHBOARD: 'DASHBOARD',
  SETUP_JD: 'SETUP_JD',
  SETUP_RESUME: 'SETUP_RESUME',
  SETUP_ROLE_CHAT: 'SETUP_ROLE_CHAT',
  SETUP_RESUME_CHAT: 'SETUP_RESUME_CHAT',
  INTERVIEW_ACTIVE: 'INTERVIEW_ACTIVE',
  INTERVIEW_FEEDBACK: 'INTERVIEW_FEEDBACK'
};