version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo "Building the project.."
      - npm run build
  post_build:
    commands:
      - echo "Copying only the contents of the production folder.."
      - rsync -a .aws/production/ .
artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - scripts/*
